# Generated by Django 4.1 on 2022-09-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('F', 'Film'), ('S', 'Series'), ('B', 'Book')], default=None, max_length=1)),
                ('title', models.CharField(default=None, max_length=250)),
                ('local_title', models.CharField(blank=True, help_text='The title of the film in its original language, blank if english', max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('members', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodes', models.IntegerField(blank=True, help_text='The number of episodes in this TV series', null=True)),
                ('rating', models.CharField(blank=True, choices=[('TBC', 'Not yet rated'), ('U', 'Universal'), ('PG', 'Parental guidance'), ('12A', 'Cinema release suitable for 12 years and over'), ('12', 'Video release suitable for 12 years and over'), ('15', 'Suitable only for 15 years and over'), ('18', 'Suitable only for adults'), ('R18', 'Adults works for licensed premises only')], help_text='The BBFC age rating of this series, rounded down from local age rating if none exists', max_length=3, null=True)),
                ('airing_status', models.CharField(choices=[('N', 'Not yet aired'), ('C', 'Currently airing'), ('F', 'Finished airing')], default=None, max_length=1)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('P', 'Prequel'), ('S', 'Sequel'), ('R', 'Related')], default=None, help_text='The relationship from media1 to media2, i.e. SEQUEL if media1 is the SEQUEL to media2', max_length=1)),
                ('media1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media1', to='media.media')),
                ('media2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media2', to='media.media')),
            ],
            options={
                'unique_together': {('media1', 'media2')},
            },
        ),
        migrations.AddField(
            model_name='media',
            name='related_media',
            field=models.ManyToManyField(blank=True, help_text='Any media related to this but not before or after it', through='media.RelatedMedia', to='media.media'),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.IntegerField(help_text='The total runtime of the film in minutes', null=True)),
                ('rating', models.CharField(blank=True, choices=[('TBC', 'Not yet rated'), ('U', 'Universal'), ('PG', 'Parental guidance'), ('12A', 'Cinema release suitable for 12 years and over'), ('12', 'Video release suitable for 12 years and over'), ('15', 'Suitable only for 15 years and over'), ('18', 'Suitable only for adults'), ('R18', 'Adults works for licensed premises only')], help_text='The BBFC age rating of this series, rounded down from local age rating if none exists', max_length=3, null=True)),
                ('release_status', models.CharField(choices=[('N', 'Not yet released'), ('C', 'Currently in cinemas'), ('F', 'Released')], default=None, max_length=1)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters', models.IntegerField(blank=True, help_text='The number of chapters in this book', null=True)),
                ('release_status', models.CharField(choices=[('N', 'Not yet published'), ('P', 'Published')], default=None, max_length=1)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
            ],
        ),
    ]
