# Generated by Django 4.1.1 on 2022-10-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmedia',
            name='relationship',
            field=models.CharField(choices=[('S', 'Sequel'), ('R', 'Related')], default=None, help_text='The relationship from media1 to media2, i.e. SEQUEL if media1 is the SEQUEL to media2', max_length=1),
        ),
    ]
